version: '3.5'
services:
  apache:
    container_name: apache
    build:
      context: ./apache
      dockerfile: Dockerfile
    privileged: true
    ports:
      - 80:80
    environment:
      WOVN_ENV: development
    volumes:
      - ./apache/log:/var/log/apache2
      - ./apache/apache2.conf:/etc/apache2/sites-enabled/apache2.conf
      - ./php.ini:/usr/local/etc/php/php.ini
      - ../:/opt/project
      - ./test:/var/www/html
    command:
      bash -c "a2enmod rewrite && sleep 5 && apache2-foreground"
    networks:
      - backend-network
networks:
  backend-network:
    name: 'backend-network'
